job('First-Maven-Project-Via-DSL'){
    description("First Maven Job generated by the DSL on ${new Date()}, theproject is a samllmaven project hosted on github")
    scm{
        git("git@github.com:Gilgamesh1/Jenkins_Upgradev3.git",master)
    }
    triggers{
        scm('* * * * *')
    }
    steps{
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publisher{
        archiveArtifacts '**/*.jar'
    }
}