pipeline{
    agent any
    stages {
        stage('Constuyendo la Aplicacion'){
            steps {
                sh 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Ahora archivando el artefacto .... "
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create TomcatDocker Iamge'){
            steps {
                sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
    }
}