pipeline{
    agent any
    stages {
        stage('Constuyendo la Aplicacion'){
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Ahora archivando el artefacto .... "
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy Applitacion Staging QA'){
            steps {
                build job: 'Deploy_ApplitacionStaging_Env'
            }
        }
        stage('Deploy to Production'){
            steps {
                timeout(time:5, unit:'DAYS'){
                    input message: 'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
    }
}