pipeline{
    agent any
    stages {
        stage('Constuyendo la Aplicacion'){
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    echo "Ahora archivando el artefacto .... "
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}