pipeline{
    agent any
    stages {
        stage('Constuyendo la Aplicacion'){
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Ahora archivando el artefacto .... "
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}